CREATE TYPE list_type AS ENUM (
    'Now',
    'Next'
);

CREATE TABLE dontforget_lists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    list_name TEXT NOT NULL,
    type list_type NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER REFERENCES dontforget_users(id) on DELETE CASCADE NOT NULL
);
