CREATE TABLE dontforget_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    user_id INTEGER REFERENCES dontforget_users(id) on DELETE CASCADE NOT NULL,
    list_id INTEGER REFERENCES dontforget_lists(id) on DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);
